### ISSUE TITLE
All ranks of Life Tap / Talent Spell Issues / Configuration Issues

### ISSUE THREAD

**Issue by jacpurg** [tkn963/mod-learnspells#1]
This version of Learn Spells does the same thing as the other versions, it teaches all ranks of Life Tap when you train rank 1 automatically.  

It also seems to ignore the configuration settings.  Based on the following settings, players should automatically learn class spells and that's it.  Instead, Druids are learning their flight form, mangle and other spells they shouldn't be.  Warriors learning stances.  Etc.  I didn't think they should be learning spells from quests they haven't completed or talents they haven't chosen.

# Learn class-specific spells
LearnSpells.ClassSpells = 1

# Learn ranks of known talents
LearnSpells.TalentRanks = 0

# Learn weapon and defense skills
LearnSpells.Proficiencies = 0

# Learn spells normally obtained from quests
LearnSpells.SpellsFromQuests = 0

Any help would be very much appreciated as would really love to use this module, but it appears to still have many bugs to sort out before it can be used in a professional environment.

**Comment by noisiver** [comment]
I use it myself and have no issues with it. I play all classes except Rogue and have had no issues at all, in fact.

If I disable SpellsFromQuests my Warrior doesn't get stances etc so that's another thing that works fine on my end.

**Comment by noisiver** [comment]
Just as a "proof", this is what happens to me when a warlock hits level 6
![image](https://github.com/noisiver/mod-learnspells/assets/5157047/282db21c-918b-46e0-badd-cc523c80c438)

I also decided to create a warrior and level it up to make sure it didn't get stances etc when hitting 10. It did not. I can't replicate a single thing you mentioned.

**Comment by jacpurg** [comment]
I apologize, there must have been confusion between my dev and I because this appears to be working as intended on our PTR now.  

Again, apologies.
